export const BOOKING_LIST_REQUEST = "BOOKING_LIST_REQUEST";
export const BOOKING_LIST_SUCCESS = "BOOKING_LIST_SUCCESS";
export const BOOKING_LIST_FAIL = "BOOKING_LIST_FAIL";

export const BOOKING_DETAILS_REQUEST = "BOOKING_DETAILS_REQUEST";
export const BOOKING_DETAILS_SUCCESS = "BOOKING_DETAILS_SUCCESS";
export const BOOKING_DETAILS_FAIL = "BOOKING_DETAILS_FAIL";

export const BOOKING_DELIVERED_REQUEST = "BOOKING_DELIVERED_REQUEST";
export const BOOKING_DELIVERED_SUCCESS = "BOOKING_DELIVERED_SUCCESS";
export const BOOKING_DELIVERED_FAIL = "BOOKING_DELIVERED_FAIL";
export const BOOKING_DELIVERED_RESET = "BOOKING_DELIVERED_RESET";

export const BOOKING_DELETE_REQUEST = "BOOKING_DELETE_REQUEST";
export const BOOKING_DELETE_SUCCESS = "BOOKING_DELETE_SUCCESS";
export const BOOKING_DELETE_FAIL = "BOOKING_DELETE_FAIL";